"""Add folder-recipe association table and foreign key references

Revision ID: 9d088dc6e2fe
Revises: fe97b13c5062
Create Date: 2024-11-11 15:46:17.491419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d088dc6e2fe'
down_revision = 'fe97b13c5062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder_recipe_association',
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('folder_id', 'recipe_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('folder_recipe_association')
    # ### end Alembic commands ###
