"""Recipe adjusted recipe model + index display of ingredients

Revision ID: fc8c8004d4b9
Revises: add05833ee91
Create Date: 2024-11-10 18:14:33.808998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8c8004d4b9'
down_revision = 'add05833ee91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spoonacular_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ready_in', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('servings', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('img_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dish_types', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('stored_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('instructions',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('ingredients',
               existing_type=sa.TEXT(),
               nullable=True)
       #  batch_op.drop_constraint('recipes_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.alter_column('ingredients',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('instructions',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('stored_at')
        batch_op.drop_column('dish_types')
        batch_op.drop_column('img_url')
        batch_op.drop_column('source')
        batch_op.drop_column('servings')
        batch_op.drop_column('ready_in')
        batch_op.drop_column('spoonacular_id')

    # ### end Alembic commands ###
